name: Update Reference Sellers Lists

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  update-sellers:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Fetch sellers.json files
        run: |
          mkdir -p reference_sellers_lists
          curl -fSL https://ads.shemedia.com/sellers.json -o reference_sellers_lists/sellers_shemedia.json
          curl -fSL https://ads.cafemedia.com/sellers.json -o reference_sellers_lists/sellers_cafemedia.json
          curl -fSL https://www.mediavine.com/sellers.json -o reference_sellers_lists/sellers_mediavine.json
          curl -fSL https://freestar.com/sellers.json -o reference_sellers_lists/sellers_freestar.json
          curl -fSL https://www.aditude.com/sellers.json -o reference_sellers_lists/sellers_aditude.json

      - name: Fetch Sincera ecosystem data
        env:
          SINCERA_API_KEY: ${{ secrets.SINCERA_API_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        run: |
          bash scripts/fetch_sincera_data.sh

      - name: Sample A2CR data
        env:
          SINCERA_API_KEY: ${{ secrets.SINCERA_API_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        run: |
          pip install requests numpy
          python scripts/sample_a2cr.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git status --porcelain | grep .; then
            git add reference_sellers_lists/*.json output/ecosystem/ecosystem.json output/raw_ac2r/* output/ac2r_analysis/*
            git commit -m "Update sellers lists and data output"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
